### PR TITLE
initial zuul conf

### PR DESCRIPTION
**Pull request by fredericlepied**

### CODE REVIEW

**Comment by sileht** [comment]
test

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Pull request merged**
